apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m0s
  resources:
    - ./apps/namespace.yaml
    - ./apps/nginx/

